### ISSUE TITLE
What if SKYAREA is unknown or not easy to calculate?

### ISSUE THREAD

**Issue by ivvv** [JohannesBuchner/nway#2]
I have two catalogues constructed in some way from sky maps. The sources were extracted from regions which were not masked, avoiding bright stars, nearby large galaxies etc. As the authors of the catalogues do not provide the actual coverage maps then it is difficult or impossible to derive the SKYAREA.

Obviously in this case the probabilistic approach won't work. I can use directly methods to do nearest neighbour search outside NWAY, but my question is if I can still use NWAY for its performance and if in my case the value of the SKYAREA could be set to an arbitrary value, e.g. 4*pi for both catalogues. And what if only one of the catalogues has well defined SKYAREA?

Take an example of cross-matching the 3XMM catalogue and the [Herschel SPIRE Point Source Catalogue](http://archives.esac.esa.int/hsa/legacy/HPDP/SPIRE/SPIRE-P/SPSC/).

**Comment by JohannesBuchner** [comment]
To estimate whether a source is there by chance, the sky density is critical. You would be able to run NWAY with an arbitrary value, but the outcome may not mean much.

Here are my suggestions in order of correctness (from worst to best):

1) Compute an approximate SKYAREA. For example you could throw all point sources against a healpix binning (see create-fake-catalogue.py for an example) and compute the fraction of filled bins ( len(numpy.unique(pix))*1./npix ). Conceivably you can derive a meaningful upper and lower bound and run NWAY twice. Possibly the differences will not be large.

2) Another problem of this catalogue is that its exposure is inhomogenous. So at a given RA/DEC, the global sky density might not be representative. It may make sense to split the catalogue by exposure (or density) into several zones, and match them individually. (1) would still apply.

3) The best would be to go back to the exposure maps and compute the sky area. (2) would still help. We do not ship automatic tools for (1) (e.g. convex hull) because it could be easily abused and give the wrong answer. It is always better if someone with in-depth knowledge of the catalogue computes/estimates the sky area.
